### ISSUE TITLE
'vibration/vibration-Swift.h' file not found

### ISSUE THREAD

**Issue by jaysson** [benjamindean/flutter_vibration#1]
#import <vibration/vibration-Swift.h> in VibrationPlugin.m throws 'vibration/vibration-Swift.h' file not found when I try to build.

What am I missing?

**Comment by benjamindean** [comment]
Looks like your project doesn't have Swift support. Try to rebuild it with Swift support and build it again.

**Comment by jaysson** [comment]
Project was created with swift support.

**Comment by c0h1b4** [comment]
Same problem here. Any instructions to rebuild the project with Swift? Or is it possible to have an Objective-C version to work?

**Comment by benjamindean** [comment]
@jaysson @c0h1b4 Do you have a line `use_frameworks!` uncommented in your Podfile?

**Comment by jaysson** [comment]
No, it is commented. Now I moved to just use HapticFeedback which is built in flutter, so can’t test immediately.

On 14-Jan-2019, at 10:06 PM, Benjamin Dean <notifications@github.com<mailto:notifications@github.com>> wrote:


@jaysson<https://github.com/jaysson> @c0h1b4<https://github.com/c0h1b4> Do you have a line use_frameworks! uncommented in your Podfile?

**Comment by smande00** [comment]
I had the same issue but had to actually add use_frameworks! manually to the podfile.

**Comment by arpandesai** [comment]
@smande00  where did you add  **use_frameworks** can you show me

**Comment by agueroveraalvaro** [comment]
Thanks! **add use_frameworks** and run **pod install**

**Comment by dark-chocolate** [comment]
@arpandesai  You can add it on the top, like this: 

```
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
use_frameworks!
```
