### ISSUE TITLE
PLEASE PLEASE FINALLY UPDATE THIS PACKAGE 

### ISSUE THREAD

**Issue by fisforfaheem** [benjamindean/flutter_vibration#116]
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\fisfo\AppData\Local\Pub\Cache\hosted\pub.dev\vibration-2.0.1\android\src\main\java\com\benjaminabel\vibration\VibrationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details

**Comment by benjamindean** [comment]
I'm aware of the issue, but as I've mentioned in the previous reports, some deprecated vibration methods are kind of needed to keep it working on the past Android versions. This warning has been there from the beginning. Does it prevent you from building the app?

**Comment by fisforfaheem** [comment]
i get it, but can you please keep it updated ( from the master ) to pub.dev

**Comment by benjamindean** [comment]
But pub.dev does have the latest version. What are you missing from it exactly?

**Comment by fisforfaheem** [comment]
[beboro] flutter pub get --no-example
Resolving dependencies...
Could not find a file named "pubspec.yaml" in https://github.com/benjamindean/flutter_vibration.git https://github.com/benjamindean/flutter_vibration/commit/69842d33a23b87f3b39b60f5fc3f0022998fefca.
Failed to update packages.
exit code 1  i cant use this how

**Comment by fisforfaheem** [comment]
[beboro] flutter pub get --no-example
Resolving dependencies...
Could not find a file named "pubspec.yaml" in https://github.com/benjamindean/flutter_vibration.git https://github.com/benjamindean/flutter_vibration/commit/69842d33a23b87f3b39b60f5fc3f0022998fefca.
Failed to update packages.
exit code 1

**Comment by fisforfaheem** [comment]
![image](https://github.com/user-attachments/assets/30c97991-6cb0-43d1-bb73-c335bd8837d2)

**Comment by benjamindean** [comment]
The subpackages are published separately. Just install it with `flutter pub add vibration`. Or, if you want to use the git ref, I guess with subfolders it's also possible, but I'm not aware how.
