### ISSUE TITLE
why cant we use latest version?

### ISSUE THREAD

**Issue by fisforfaheem** [benjamindean/flutter_vibration#117]
[beboro] flutter pub get --no-example
Resolving dependencies...
Could not find a file named "pubspec.yaml" in https://github.com/benjamindean/flutter_vibration.git 69842d33a23b87f3b39b60f5fc3f0022998fefca.
Failed to update packages.
exit code 1

**Comment by benjamindean** [comment]
The plugin is separated by platform with one common interface. There are `vibration` and `vibration_web` subfolders.

**Comment by fisforfaheem** [comment]
I got it! thanks! I love this package for microinteractions, I use it daily, I wish it has some more options(which you can ask sonnet)
