### ISSUE TITLE
Depricated warning

### ISSUE THREAD

**Issue by CeciMza** [benjamindean/flutter_vibration#14]
I am getting this warning when I run flutter:

Note: /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.2.1/android/src/main/java/com/benjaminabel/vibration/VibrationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by benjamindean** [comment]
Most likely it's about the `vibrate` method. The old method is marked as deprecated, but as far as I know, still works on the old Android versions.

**Comment by CeciMza** [comment]
oh so I can just leave it as it is?

**Comment by benjamindean** [comment]
Yes, it's just a warning which you can ignore. I'll try to get rid of it, if possible.

**Comment by malikdoksoz** [comment]
> Yes, it's just a warning which you can ignore. I'll try to get rid of it, if possible.

Thanks

**Comment by hrashdan** [comment]
![image](https://user-images.githubusercontent.com/46036841/66263818-a9081000-e801-11e9-8e72-e378c598555c.png)

![image](https://user-images.githubusercontent.com/46036841/66263829-f1bfc900-e801-11e9-9475-fd1dd8702642.png)

**Comment by jdeltoft** [comment]
I get this error, and when I build apks (debug or release) and side install them, it fails to vibrate on two different android phones I've tested so far.

**Comment by saddy001** [comment]
I'm also getting the deprecation warning.

**Comment by benjamindean** [comment]
This warning shouldn't affect anything because there is a check for API version. I'll check why it even shows up, but I can do it only next week. Sorry for the inconvenience. The plugin should still work as expected.

**Comment by malikdoksoz** [comment]
> This warning shouldn't affect anything because there is a check for API revision to support old Android versions. The only thing I can do is add `@SuppressWarnings` to the method call. But I can only do it next week. Sorry for the inconvenience. The plugin should still work as expected.

Cool
