### ISSUE TITLE
Widget tests on vibration plugin

### ISSUE THREAD

**Issue by flutteradv** [benjamindean/flutter_vibration#19]
what is the  name for MethodChannel ? I used following package name in widget tests with no success:
```
MethodChannel channel =
      const MethodChannel('com.benjaminabel.vibration');
  channel.setMockMethodCallHandler((MethodCall methodCall) async {
    print("=============>>>>> $methodCall  <<<<<===================");
  });
```

**Comment by benjamindean** [comment]
Hey! It's just `vibration` as specified [here](https://github.com/benjamindean/flutter_vibration/blob/master/android/src/main/java/com/benjaminabel/vibration/VibrationPlugin.java#L18).

**Comment by flutteradv** [comment]
sorry I just found now thanks a lot
