### ISSUE TITLE
Does not seem to work in the background

### ISSUE THREAD

**Issue by wilkomanger** [benjamindean/flutter_vibration#22]
When calling `Vibration.vibrate` in the background (from a callback from `firebase_messaging`), nothing seems to happen.

**Comment by benjamindean** [comment]
Are you able to print something out or play a sound from that callback?

**Comment by wilkomanger** [comment]
Yes, printing works and sounds can also be played.

**Comment by wilkomanger** [comment]
Actually, it might be a device specific issue. It works on a Samsung Galaxy S9, but not on a Google Pixel 3a.

**Comment by benjamindean** [comment]
Hmmm. Seems like I have to do a small research about it. It's not the first time it doesn't work on Pixel devices.

**Comment by chenparty** [comment]
I found the same problem on my huawei-mate30,  maybe its caused by android 10.   The link is as follows: https://www.jianshu.com/p/3ec9158b2041

**Comment by maxmblack** [comment]
Same problem appears on OnePlus 7 Pro with Android 10. Couldn't test it on other devices

**Comment by yairsafe** [comment]
Problem appears on Android 10 devices. any solution?

**Comment by benjamindean** [comment]
@yairsafe @flashawy @maxmblack I think it's related to Android 10 and above, but I don't have the solution at the moment.

**Comment by wanghaiyang5241** [comment]
> @yairsafe @flashawy @maxmblack我认为它与Android 10及更高版本有关，但目前没有解决方案。

i have pr to you,please look for you

**Comment by benjamindean** [comment]
@yairsafe @flashawy @maxmblack I merged the PR provided by @wanghaiyang5241, but haven't released a new version yet. Can you, kindly, test it on your devices by installing it from master branch directly? 

Just specify it in your `pubspec.yml`: 

```
vibration:
    git:
      url: git@github.com:benjamindean/flutter_vibration.git
      ref: master
```

**Comment by maxmblack** [comment]
@benjamindean sorry for that late response. I just tested on an OnePlus Android 10 and it worked 
Could you update the package version? 
Thank you!

**Comment by yairsafe** [comment]
I tested now on an Samsung S9 (OS Version android 10) and its worked! thanks a lot!

**Comment by benjamindean** [comment]
@yairsafe @flashawy @maxmblack Version 1.5.0 released.
