### ISSUE TITLE
bool operator for hasVibrator

### ISSUE THREAD

**Issue by nicolasvahidzein** [benjamindean/flutter_vibration#23]
i get an error when i try this:

```
               if (Vibration.hasVibrator()) {
				Vibration.vibrate(duration: 500);
				return true;
		}
```

saying 

Conditions must have a static type of 'bool'.
Try changing the condition.

**Comment by benjamindean** [comment]
All the methods are `Futures`. Meaning, you should `await` them. You can always check it by checking the function return type. I released a new version with updated README.

**Comment by nicolasvahidzein** [comment]
Ok Benjamin, thanks. Will try that now.
