### ISSUE TITLE
Depends on flutter_test

### ISSUE THREAD

**Issue by joknjokn** [benjamindean/flutter_vibration#24]
Hi,

Does this plugin have to depend on flutter_test ? Flutter_test depends on an old version of the image plugin, which I now can't upgrade because this vibration plugin depends on flutter_test.

```
Because no versions of vibration match >1.2.3 <2.0.0 and vibration 1.2.3 depends on flutter_test any from sdk, vibration ^1.2.3 requires flutter_test any from sdk.

And because every version of flutter_test from sdk depends on image 2.1.4, vibration ^1.2.3 requires image 2.1.4.
```

**Comment by benjamindean** [comment]
@joknjokn Thank you for noticing! I moved `flutter_test` to dev_dependencies and released a new version. Please check if it resolves the issue.

**Comment by joknjokn** [comment]
It seems to work. Thanks!
