### ISSUE TITLE
It seem doesn't work

### ISSUE THREAD

**Issue by disburden** [benjamindean/flutter_vibration#27]
Here is my code:
```
	void _submmit() async {
		if (await Vibration.hasVibrator()) {
			print("111");
			Vibration.vibrate(duration: 500);
			if (await Vibration.hasAmplitudeControl()) {
				Vibration.vibrate(amplitude: 128);
			}
		} else {
			print("222");
		}
	}
```
The log printed "111",but the phone didn't vibrate.
My phone is :iPhone 7
IOS: 13.3.1

**Comment by benjamindean** [comment]
Does running `Vibration.vibrate()` without arguments has the same results?

**Comment by ngothanhtai** [comment]
I have the same problem. And I run without arguments @benjamindean.

**Comment by benjamindean** [comment]
@ngothanhtai What is the device?

**Comment by ngothanhtai** [comment]
@benjamindean the `Vibrate.vibrate()` does not work on my iPhone XR but it works when using `Vibrate.feedback(FeedbackType.impact);`

**Comment by ngothanhtai** [comment]
@benjamindean I am sorry, I am using other package `flutter_vibrate` that have `Vibrate.feedback(FeedbackType.impact);`.

**Comment by akhiltiwari16** [comment]
Please consider that default vibration duration is only 500ms. It might actually be working but you aren't noticing it because it vibrates only for 500ms. Try increasing that duration.

**Comment by disburden** [comment]
It seems to be work, I don't know if it was the reason why I upgraded the iOS version, anyway, it's normal a few days ago.
I'll close it first
