### ISSUE TITLE
swift 5 conversion on ios

### ISSUE THREAD

**Issue by nicolasvahidzein** [benjamindean/flutter_vibration#29]
hello, i'm getting a warning about swift 5 conversion on ios, anything i can do to get rid of that message?

i'm using v 1.2.2. 

Thanks.

**Comment by benjamindean** [comment]
Hey! What warning exactly?

**Comment by nicolasvahidzein** [comment]
i need to run it again and send it to you. Sorry for that omission.

**Comment by nicolasvahidzein** [comment]
so it shows up as a pod needing swift 5 conversion but it doesn't work in converting it.

**Comment by benjamindean** [comment]
Does it happen during the build? What are your exact steps? Also, the output of `flutter doctor` will be very helpful!

**Comment by nicolasvahidzein** [comment]
Its a warning when i open xcode. Ok ill send you the output

**Comment by nicolasvahidzein** [comment]
Leonidas:~ nicolaszein$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.17.0 at /Applications/Development/Flutter
    • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nicolaszein/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode-11.3.app/Contents/Developer
    • Xcode 11.3, Build version 11C24b
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 45D73A2F-BB34-4663-B94D-2D0DE1FC496F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**Comment by benjamindean** [comment]
The plugin is using Swift 5.0 now. You can try again.

**Comment by nicolasvahidzein** [comment]
Ok will check thank you!!
