### ISSUE TITLE
EXC_BAD_ACCESS on iPhone SE since 1.3.0

### ISSUE THREAD

**Issue by HugoHeneault** [benjamindean/flutter_vibration#32]
Hi there! THanks for your cool vibration plugin 👍 

My app won't load on iPhone SE simulator since 1.3.0 update.

I have an `EXC_BAD_ACCESS` error. Working on a PR. :-)

**Comment by benjamindean** [comment]
That was fast! Thank you! Will release a new version in ~5 minutes.

**Comment by HugoHeneault** [comment]
@benjamindean As I don't have an Haptic phone would you check if it still work with my change? :-)

**Comment by HugoHeneault** [comment]
Merging was really fast too 👍

**Comment by benjamindean** [comment]
Me neither, actually. But it should work since those variables weren't used anyway.
