### ISSUE TITLE
Add a `supportCustomVibrations` method

### ISSUE THREAD

**Issue by Skyost** [benjamindean/flutter_vibration#34]
Hey.

I love the latest plugin update that added the CoreHaptics support. Would it be possible for you to create a method (can be named `supportCustomVibrations` or whatever) which would return :

* `true` on Android.
* `true` on CoreHaptics iOS devices (and `false` on older devices).

This way, we could have a better control on which devices we can play custom vibrations, and on which devices it's not possible to do so.

Thanks !

**Comment by benjamindean** [comment]
Sure! Good idea. Will implement it as soon as I can.

**Comment by Skyost** [comment]
Just submitted a pull request that should do the job.

**Comment by benjamindean** [comment]
Closed in #35
