### ISSUE TITLE
How to control intensity of vibration on iOS?

### ISSUE THREAD

**Issue by Livinglist** [benjamindean/flutter_vibration#38]
I tried to set amplitude but the intensity doesn't seem to change. on iOS 14.

**Comment by ThibautSilva** [comment]
Same for me, do you have a response ? thanks

**Comment by benjamindean** [comment]
> Same for me, do you have a response ? thanks

There was another related issue. Which iPhone are you testing on? If will only work on iPhone 8 out newer.

**Comment by ThibautSilva** [comment]
iPhone 11, what is the good parameter ? And what are values for this variable ? Thanks

**Comment by Livinglist** [comment]
> Same for me, do you have a response ? thanks

This is what I did:

```
Vibration.vibrate(pattern: [0, 5], intensities: [255]);
```

You can change the intensity this way.

**Comment by nt4f04uNd** [comment]
@Livinglist did you make it vibrate 5 milliseconds?
