### ISSUE TITLE
iOS build fails: fatal error: 'vibration/vibration-Swift.h' file not found

### ISSUE THREAD

**Issue by samycodes** [benjamindean/flutter_vibration#39]
When I run my application for iOS it fails with this error.

`
flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.4.0/ios/Classes/VibrationPlugin.m:2:9: fatal
    error: 'vibration/vibration-Swift.h' file not found
    #import <vibration/vibration-Swift.h>
`

Anyone who can help me to resolve this error?

**Comment by benjamindean** [comment]
See #1
