### ISSUE TITLE
when i use vibration in a flutterModule.it tips a error like this.

### ISSUE THREAD

**Issue by qinxuliang** [benjamindean/flutter_vibration#41]
![image](https://user-images.githubusercontent.com/5266488/91513063-01626780-e916-11ea-9fb4-41bd72d786ea.png)

**Comment by wanghaiyang5241** [comment]
#import "VibrationPlugin.h"
// #import <vibration/vibration-Swift.h>
#if __has_include(<vibration/vibration-Swift.h>)
#import <vibration/vibration-Swift.h>
#else
#import "vibration-Swift.h"
#endif

@implementation VibrationPlugin
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
  [SwiftVibrationPlugin registerWithRegistrar:registrar];
}
@end

**Comment by wanghaiyang5241** [comment]
you need change at xcode

**Comment by wanghaiyang5241** [comment]
@qinxuliang
