### ISSUE TITLE
Haptic vibration not supported on iphone 7 

### ISSUE THREAD

**Issue by silversquall** [benjamindean/flutter_vibration#42]
Hi,

I have : 

- An iphone 7 with ios 13.3.1
- Enabled haptic in the settings

await Vibration.hasCustomVibrationsSupport()) --> returns false --> i can't use the haptic feature.

2 questions:

1) On which device have you tested ? 

2)  are you supporting ios 14 ?

thx.

**Comment by benjamindean** [comment]
Hey!
Haptics only work on iPhone 8 and above due to hardware limitations.

**Comment by silversquall** [comment]
surprising as the iphone 7 is supposed to be haptic compatible.
thx for the reply.
