### ISSUE TITLE
Vibration.hasVibrator() promise false in iOS

### ISSUE THREAD

**Issue by hrshs** [benjamindean/flutter_vibration#50]
‍‍‍`Vibration.hasVibrator()` in iOS always promis false.
I've checked swift code and you get the value of `hasVibrator` from `TARGET_OS_SIMULATOR == 1` and then this code always returns false in physical iOS device.
What's wrong?

**Comment by benjamindean** [comment]
Yeah, seems like it's a bug. I'll fix it as soon as I can.

**Comment by ZhuBoao** [comment]
I am having the same issue. I had to downgrade the package for now. Appreciate very much if you can fix it.

**Comment by hrshs** [comment]
@ZhuBoao I called `Vibration.hasVibrator()` only in android platform. I think it didn't cause any problem because the developer just check the device is physical or simulator.

**Comment by ZhuBoao** [comment]
> @ZhuBoao I called `Vibration.hasVibrator()` only in android platform. I think it didn't cause any problem because the developer just check the device is physical or simulator.

I guess the iPad or maybe some iPods running iOS doesn't have any vibrator, so there should be a proper fix on iOS as well. Anyway, if the app only runs on iPhones, I agree we could safely assume that `hasVibrator()` return true.

**Comment by benjamindean** [comment]
@ZhuBoao Which version are you downgrading it to?

**Comment by benjamindean** [comment]
@ZhuBoao I created #52 for testing. If you have a physical device to test it on - I would really appreciate it. I don't have any, so that's why iOS code is kind of neglected.

**Comment by benjamindean** [comment]
I just published version 1.7.3. Hope it works!

**Comment by ZhuBoao** [comment]
@benjamindean I just tested `1.7.3` on my iPhone X, and it works. Thanks!

**Comment by benjamindean** [comment]
Seems like the issue was resolved. Simulator env detection was migrated from Objective-C by mistake.
