### ISSUE TITLE
how to use intensifies

### ISSUE THREAD

**Issue by nt4f04uNd** [benjamindean/flutter_vibration#55]
i want just to vibrate for a few seconds and all this time that it intensifies friom 1 to 255, or rather, reversely, goes from 255 to 1
from you readme i thought that to perform that i'm supposed to do just that

```dart
Vibration.vibrate(
  duration: duration,
  intensities: reverse ? const [255, 1] : const [1, 255],
);
```

but it doesn't seem to work and that's confusing

upd: testing on iphone x

**Comment by benjamindean** [comment]
You have to provide the `pattern` for that. In you example, it'll vibrate only once.

**Comment by nt4f04uNd** [comment]
@benjamindean so what's the correct code for the behavior i want to achieve?

i still don't understand
does intensifies automatically interpolate the vibration values and this will be correct?
```dart
Vibration.vibrate(
  duration: duration,
  pattern: [0, duration.inMilliseconds],
  intensities: reverse ? const [255, 1] : const [1, 255],
);
```
or i have to specify all of them
```dart
final intensities = List.generate(255, (i) => i + 1);
Vibration.vibrate(
  duration: duration,
  // generates a pattern [0, 1, 0, 2, 0, 3, 0, 4, 0, 5, .......... ]
  pattern: List.generate(255 * 2, (i) => i).map((el) => el % 2 == 0 ? 0 : el ~/ 2 + 1).toList(),
  intensities: reverse ? intensities.reversed.toList() : intensities,
);
```

which is correct?

**Comment by benjamindean** [comment]
@nt4f04uNd Have you checked the examples in README? You should specify either duration or pattern in milliseconds with intensities list.

**Comment by nt4f04uNd** [comment]
@benjamindean yep, i just missed the thing with the you have to either use duration and amplitude, or pattern and intensifies

all works fine for me now

but, i now i think you should either add assertions for that, or make another method and move the pattern vibration in there. current api is a little bit confusing imo
