### ISSUE TITLE
[Question] How to vibrate indefinitely?

### ISSUE THREAD

**Issue by VictorUvarov** [benjamindean/flutter_vibration#56]
How do I vibrate forever? Do I need my own loop or can I do something with the `repeat` param in `Vibrator.vibrate`?

**Comment by merelj** [comment]
any info on "repeat" would be great :/

**Comment by benjamindean** [comment]
@VictorUvarov @merelj I think it's not really possible to vibrate "forever". You can probably vibrate for 24 hours like that: `Vibration.vibrate(duration: Duration(hours: 24).inMilliseconds);`.

**Comment by merelj** [comment]
@benjamindean thank you for the response.

somehow when I call 
`Vibration.vibrate(duration: const Duration(hours: 1).inMilliseconds);`
it only vibrates for about 500ms and then stops.

I think, the question is actually "how do I make the phone vibrate for a long time using a pattern?".

i.e. 500ms vibration - 500 ms pause - 500ms vibration - 500ms pause and so on.
do i have to set [500, 500, 500, 500, ...] in pattern or is there an easier way (list might get a bit long if phone should vibrate for a minute or longer: 60s * 2 = 120 of those 500s)? 🤔

**Comment by benjamindean** [comment]
@merelj What happens when you pass 0 as a `repeat` argument?

**Comment by merelj** [comment]
nothing changes: I still get one short vibration
here's my code if it helps at all:
![image](https://user-images.githubusercontent.com/3993495/106587880-34f78c80-655b-11eb-9cbe-585e0f145328.png)

**Comment by merelj** [comment]
I should say thay stop is called after a long time after vibration is over by another function, sorry for confusion 🤦

**Comment by benjamindean** [comment]
@merelj What platform are you testing it on?

**Comment by merelj** [comment]
Thank you for your help 🙇 
I'm testing it on a real phone with [android 10 QP1A.190711.020](https://betawiki.net/wiki/Android_10_build_QP1A.020_(OneUI))

**Comment by merelj** [comment]
Thank you for your help 🙇 

Turns out my problem was with ConnectionService on Android side of things.
If it helps anyone, the problem was that I should have set connection state to "ringing": otherwise it blocks phone vibration.

To answer the original question:
`Vibration.vibrate(pattern: [500, 500], repeat: 0);` did exactly what I needed 🙇

**Comment by VictorUvarov** [comment]
I tested `Vibration.vibrate(pattern: [500, 500], repeat: 0);` on Android 11 (Google Pixel 2 XL) and iOS 14.0.1 (iPhone 11).
It only repeats on Android.

My current solution has been to just use a periodic timer
```dart
_timer = Timer.periodic(const Duration(milliseconds: 1500), (timer) {
      Vibration.vibrate(pattern: [500, 1000], repeat: 0);
    });
```
