### ISSUE TITLE
Vibration works without permission on Android real device

### ISSUE THREAD

**Issue by roeniss** [benjamindean/flutter_vibration#57]
In debug mode, My android phone is vibrated by flutter/dart codes. Suddenly I realized that I didn't edit xml for permission at all. Is this normal behavior? 👀

I didn't touch debug/main/profile AndroidManifest.xml at all.

**Comment by benjamindean** [comment]
It should still ask the permission in production mode. For debug mode, it's handled [here](https://github.com/benjamindean/flutter_vibration/blob/master/vibration/android/src/main/AndroidManifest.xml).

**Comment by roeniss** [comment]
Ah, Thank you @benjamindean ! Have a nice day :) I'll close this issue.
