### ISSUE TITLE
1.7.4-nullsafety.0 vibration problems on ios

### ISSUE THREAD

**Issue by nt4f04uNd** [benjamindean/flutter_vibration#58]
during development of my app i pass qa on these devices and then on relese just bumped the version from `1.7.3` to `1.7.4-nullsafety.0`

after app released i received a feedback that vibration is not working on these devices:
* iPhone X
* iPhone SE 2020

is it possible that there were any changes that might have broken the plugin for these?

**Comment by benjamindean** [comment]
Only on these devices? That's unlikely, but I'll check as soon as I can.

**Comment by nt4f04uNd** [comment]
these are only i recieved feedback about. if there's an issue with plugin, it's likely it affects more (or all) ios devices

**Comment by benjamindean** [comment]
I'm not sure what's going on here. `nullsafety` branch doesn't change much. Are you sure it works on older versions?

**Comment by nt4f04uNd** [comment]
no, i think i actually added one line of code, except of changing the version, that is before vibration i also called Vibration.cancel(). i think this was the problem, i am not sure if this was a bug, but looks weird

**Comment by nt4f04uNd** [comment]
just test if you can reproduce this - call awaited cancel and then vibrate, if there's no problem then close the issue

**Comment by nt4f04uNd** [comment]
by the way, what's might be happening here is https://github.com/benjamindean/flutter_vibration/issues/54 . i asked my qa team to retest

**Comment by benjamindean** [comment]
I don't have a physical iOS device to test on. So if you still have that problem - it's a bug.

**Comment by nt4f04uNd** [comment]
Sorry, I don't work on this project anymore so don't know about it. Anyways I suggest to check that per my comment https://github.com/benjamindean/flutter_vibration/issues/58#issuecomment-812854151

**Comment by dark-chocolate** [comment]
It's also not vibrating on Android. Should I file a new issue?

Tested on Samsung Galaxy S20+ (Android 10) in both debug and release mode.

**Comment by dark-chocolate** [comment]
Make sure the vibration is turned on on both Android and iOS. 

### Android: 

![photo_2021-06-18 16 09 41](https://user-images.githubusercontent.com/40364434/122574187-b0ac2e80-d04f-11eb-940e-a09a715ce2f6.jpeg)

### iOS:

![photo_2021-06-18 16 09 44](https://user-images.githubusercontent.com/40364434/122574184-b0139800-d04f-11eb-9a66-15a90635b9a5.jpeg)
