### ISSUE TITLE
Amplitude isn't controlled in iOS

### ISSUE THREAD

**Issue by luckv** [benjamindean/flutter_vibration#61]
Even if `hasAmplitudeControl()` returns `true` in iOS, calling `vibrate()` with a custom amplitude parameter doesn't variate the amplitude of the generated vibration. On Android it works correctly

### Tested with
Flutter 2.2.1 
Vibration 1.7.3
iPhone 6S with iOS 14.5.1, the only one that I have

**Comment by z759341385** [comment]
any progress？

**Comment by benjamindean** [comment]
Hey! Sorry for the long wait. I'm unable to test it on iOS, St the plugin has only been tested on Android. As far as I know, iOS is very restrictive in that sense. It depends on the device and iOS version too.

**Comment by benjamindean** [comment]
Closed because it won't work on iPhone 6S (the device that I've been able to test it on).
