### ISSUE TITLE
Vibration.cancel() doesn't work on iOS

### ISSUE THREAD

**Issue by miri-red** [benjamindean/flutter_vibration#63]
I have vibration turned on with a pattern but in some cases I want the vibration to stop earlier, so I use Vibration.cancel().
On android it works great but on iOS it seems to continue to vibrate until the pattern is done.

**Comment by baobao2304** [comment]
hi benjamindean  what do you think about  AudioServicesDisposeSystemSoundID(kSystemSoundID_Vibrate) ?

**Comment by benjamindean** [comment]
@baobao2304 That might work, but not for the pattern unfortunately.

**Comment by baobao2304** [comment]
@benjamindean  
I think this is not bad , you can try that  , its worked with me  .  

bool isCheckStop = false;
int counter = 0;
Timer? timer;

void startVibrationIncommingcallIOS(){
  timer = Timer.periodic(Duration(seconds: 1), (timer) {
    if (counter < 20) {

      if(isCheckStop) {
        isCheckStop = false;
        counter = 0 ;
        timer.cancel();
      }
      else{
        if(counter % 2 == 0) {
          Vibration.vibrate(duration: 500);
        }
        else {
          Vibration.vibrate(duration: 1000);
        }
      }
    } else{

      timer.cancel();
      counter = 0 ;

    }
  });
}

void stopVibrationIncomingCallIOS(){
  isCheckStop = true;
}


void startRingAndVibrateIncomingCall(){
  if(Platform.isAndroid){
    Vibration.vibrate(
      pattern: List.generate(20, (index) => index % 2 == 0 ? 500 : 1000),
    );
  }else{
    startVibrationIncommingcallIOS();
  }
}

void stopRingAndVibrateIncomingCall() {
  if(Platform.isAndroid){
    Vibration.cancel();
  }else{
    stopVibrationIncomingCallIOS();
  }
}

**Comment by baobao2304** [comment]
I think this is not bad , you can try that , its worked with me .
```
bool isCheckStop = false;
int counter = 0;
Timer? timer;

void startVibrationIncommingcallIOS(){
timer = Timer.periodic(Duration(seconds: 1), (timer) {
if (counter < 20) {

  if(isCheckStop) {
    isCheckStop = false;
    counter = 0 ;
    timer.cancel();
  }
  else{
    if(counter % 2 == 0) {
      Vibration.vibrate(duration: 500);
    }
    else {
      Vibration.vibrate(duration: 1000);
    }
  }
} else{

  timer.cancel();
  counter = 0 ;

}
});
}

void stopVibrationIncomingCallIOS(){
    isCheckStop = true;
}

void startRingAndVibrateIncomingCall(){
    if(Platform.isAndroid){
        Vibration.vibrate(
        pattern: List.generate(20, (index) => index % 2 == 0 ? 500 : 1000));
    }else{
        startVibrationIncommingcallIOS();
    }
}

void stopRingAndVibrateIncomingCall() {
    if(Platform.isAndroid){
        Vibration.cancel();
    }else{
        stopVibrationIncomingCallIOS();
    }
}
```

**Comment by baobao2304** [comment]
@benjamindean  I think this is not bad , you can try that , its worked with me .
```
bool isCheckStop = false;
int counter = 0;
Timer? timer;

void startVibrationIOS(){
timer = Timer.periodic(Duration(seconds: 1), (timer) {
if (counter < 20) {

  if(isCheckStop) {
    isCheckStop = false;
    counter = 0 ;
    timer.cancel();
  }
  else{
    if(counter % 2 == 0) {
      Vibration.vibrate(duration: 500);
    }
    else {
      Vibration.vibrate(duration: 1000);
    }
  }
} else{

  timer.cancel();
  counter = 0 ;

}
});
}

void stopVibrationIOS(){
    isCheckStop = true;
}

void startVibrate(){
    if(Platform.isAndroid){
        Vibration.vibrate(
        pattern: List.generate(20, (index) => index % 2 == 0 ? 500 : 1000));
    }else{
        startVibrationIOS();
    }
}

void stopVibrate() {
    if(Platform.isAndroid){
        Vibration.cancel();
    }else{
        stopVibrationIOS();
    }
}
```
