### ISSUE TITLE
Null check operator called on null Value

### ISSUE THREAD

**Issue by umersaddiq** [benjamindean/flutter_vibration#66]
On  Vibration.vibrate() it throws a message **null check operator called on null value**

Flutter Version **2.8.1**
Dart Version **2.15.1**

**Comment by dVeki** [comment]
I had the same issue on my web project using flutter null safety.
This is the code used for solution:
`try {
            bool? hasVibration = await Vibration.hasVibrator();
            if (hasVibration != null && hasVibration) {
              bool? hasCustomVibration =
                  await Vibration.hasCustomVibrationsSupport();
              if (hasCustomVibration != null && hasCustomVibration) {
                await Vibration.vibrate(duration: c.duration!);
              } else {
                await Vibration.vibrate();
              }
            }
          }...
`

**Comment by benjamindean** [comment]
Should be solved in the latest version.
