### ISSUE TITLE
uri=org-dartlang-untranslatable-uri:package%3Avibration%2Fvibration.dart 

### ISSUE THREAD

**Issue by adnanatif** [benjamindean/flutter_vibration#67]
while try to make a iOS build it crash due to this error-->
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Avibration%2Fvibration.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:623:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:763:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:586:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>
Failed to package /Users/appledev/Desktop/flutter/flutterClient.

**Comment by benjamindean** [comment]
Have you been able to solve it? If not, please, provide an example snippet.
