### ISSUE TITLE
Vibration not working in first few calls

### ISSUE THREAD

**Issue by dovahkiin98** [benjamindean/flutter_vibration#68]
I tried to add this plugin to my app, and tested another one. Both had the same issue on iOS and web.

I basically made it vibrate when clicking a button. On few first clicks, nothing happens, but then suddenly the vibration works.

What could be the issue? I'm just calling `Vibration.vibrate()`, not even bothering with the custom duration overload, and not waiting for anything, it's just that function

**Comment by benjamindean** [comment]
If it's not isolated to one package, I would recommend using it inside the async loop. So, you'll have to await for the `vibrate` call. I'm not sure, but I think that's how Flutter handles its async calls.

**Comment by dovahkiin98** [comment]
@benjamindean Not sure how awaiting the call helps? I'm not waiting for the response. Also, it works fine on Android, so it's not the code, it's the platform

**Comment by benjamindean** [comment]
Yeah, iOS is behaving quite weirdly, even according to the reported issues here. I'm unable to test it on a real iOS device, so I'll take a look at the code I've more, but not promising that it can be fixed. Meanwhile, try to awaiting for the call.
