### ISSUE TITLE
Doesn't work with Flutter 3.3.0

### ISSUE THREAD

**Issue by ashemetov** [benjamindean/flutter_vibration#73]
Got following error:

The current Dart SDK version is 2.18.0.

Because app depends on vibration 1.7.5 which requires SDK version >=2.12.1 <=2.17.6, version solving failed.
pub get failed (1; Because app depends on vibration 1.7.5 which requires SDK version >=2.12.1 <=2.17.6, version solving failed.)

**Comment by Asscre** [comment]
me too.

**Comment by benjamindean** [comment]
Please update the package to the latest version. Should work now.
