### ISSUE TITLE
Got some feedback from Pixel 2 and Pixel 3 users to not working

### ISSUE THREAD

**Issue by JigneshPatel23** [benjamindean/flutter_vibration#8]
Does anyone have any idea about the same? Any fixes or clues?

**Comment by benjamindean** [comment]
@JigneshPatel23 Which `flutter_vibration` and `flutter` version are you using?

**Comment by JigneshPatel23** [comment]
Yes, I am on below versions.
Flutter (Channel stable, v1.5.4-hotfix.2)
vibration: 1.1.0

**Comment by benjamindean** [comment]
Can you, please, try version `1.0.2`? Migration to AndroidX could be the cause.

**Comment by JigneshPatel23** [comment]
Sure, I will try that version.

**Comment by benjamindean** [comment]
@JigneshPatel23 Did it work? It's a bug in any case - just trying to understand what's the cause of it.
