### ISSUE TITLE
Impossible to do a small vibration

### ISSUE THREAD

**Issue by martinpelli** [benjamindean/flutter_vibration#88]
There is no way to do a small vibration, like when spinning a wheel to change time, some apps have a very very small vibration. I tried to use this package to achieve that, but if I call Vibration.vibrate(duration: 20, amplitude: 50) the vibration is huge and awful.

**Comment by Hadi-Osman** [comment]
When I do Vibration.vibrate(duration: 15, amplitude: 64) I get a short and precise vibration, I am using a Samsung Galaxy S10+

**Comment by martinpelli** [comment]
> When I do Vibration.vibrate(duration: 15, amplitude: 64) I get a short and precise vibration, I am using a Samsung Galaxy S10+

Nevermind, I found that this is not for what I Wanted, for anyone looking for this, flutter has **Haptics**, so you should search for **Haptics** and not vibration

**Comment by xihuny** [comment]
@martinpelli but haptics only have 4 options right? what if I want a different duration?
