### ISSUE TITLE
Problem with ios 16

### ISSUE THREAD

**Issue by Mixelon-tera** [benjamindean/flutter_vibration#89]
My Flutter app works well with IOS 15.4.1
But not work with IOS 16.1.1 and  IOS 16.5.1

I think it has a problem with IOS 16, Anyone has this problem?

**Comment by hmarat** [comment]
@Mixelon-tera any news?

**Comment by FWiner** [comment]
same problem here

**Comment by benjamindean** [comment]
Hey, @Mixelon-tera ! Sorry for the delay. Do you perhaps have any error logs or it happens without an error?

**Comment by codeOfJannik** [comment]
For us any version of the package above 1.8.1 in combination with iOS 16 causes UI lags on repeated vibrations. No errors in the logs visible for us

**Comment by benjamindean** [comment]
> For us any version of the package above 1.8.1 in combination with iOS 16 causes UI lags on repeated vibrations. No errors in the logs visible for us

Do you have an example? The part of the code triggering vibration will work.
