### ISSUE TITLE
Support OpenHarmony 

### ISSUE THREAD

**Issue by zmtzawqlp** [benjamindean/flutter_vibration#99]
Flutter will support OpenHarmony base on Flutter 3.7.12. it comes from https://gitee.com/openharmony-sig/flutter_flutter.

If it's okay, I can help complete the implementation of this platform.

It seems that vibration has no limitation of Flutter version. So i can work on the latest code of vibration, right?

**Comment by benjamindean** [comment]
Hey! Yes, that would be great. The latest code is good to go.

**Comment by zmtzawqlp** [comment]
ok, i will fire a pr after i finish it. thanks
